apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-config-apps
    labels:
        tier: frontend
data:
    config: server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;
        location / {
        root   /var/www/apps.symper.vn;
        index  index.html index.htm;
        }
        }
