export default {
    input: {
        search: 'mdi-magnify',
        task: '',
        my_application: 'mdi mdi-format-list-checkbox',
        workflow_definition: 'mdi mdi-lan',
        document_definition: 'mdi mdi-file-document-edit-outline',
        document: 'mdi mdi-import',
        document_instance: 'mdi mdi-file-document-outline',
        BI: 'mdi-view-dashboard-outline',
        orgchart: ' mdi mdi-office-building-outline',
        lisTaskToDo: 'mdi-sticker-check-outline',
        timeTable: 'mdi-calendar-month-outline',
        knowledge: 'mdi mdi-file-certificate-outline',
        file: 'mdi-upload-outline',
        userManager: 'mdi-account-cog-outline',
        user: 'mdi mdi-account-cog-outline',
        accessManager: 'mdi-shield-key-outline',
        application: 'mdi mdi-widgets-outline',
        account: 'mdi mdi-account-multiple-outline',
        process_definition: 'mdi mdi-sitemap',
        application_definition: 'mdi mdi-apps',
        application: 'mdi mdi-apps',
        syql: 'mdi mdi-alpha-f',
        dataflow: 'mdi mdi-arrange-send-to-back',
        comment: 'mdi-comment-outline',
        file: 'mdi mdi-file-upload-outline',
        dashboard: 'mdi mdi-view-dashboard',
        action_pack: ' mdi mdi-package-variant-closed',
        import: 'mdi mdi-import',
        dataset: 'mdi mdi-database-outline',
        workflow_instance: 'mdi mdi-lan',
        taskBPM: 'mdi-lan',
        task: 'mdi-pentagon-outline',
        role: 'mdi mdi-account-circle-outline',
        time_sheet: 'mdi mdi-calendar-month-outline',
        stateflow_flow: 'mdi mdi-state-machine',
        data_connector: "mdi mdi-power-plug",
        filter: 'mdi mdi-filter-outline',
        permission_pack: 'mdi mdi-shield-account-variant-outline',
        action_pack: 'mdi mdi-tune',
        system_role: 'mdi mdi-account-circle-outline',
        // orgchart_role: 'mdi mdi-account-circle-outline',
    },
    mobile_config: {
        select: 'mdi-list-status',
        table: 'mdi-table',
        date: 'mdi-calendar-range',
        dateTime: 'mdi-clipboard-text-clock-outline',
        percent: 'mdi-percent-outline',
        file: 'mdi-table',
        inputFilter: 'mdi-format-list-checkbox',
        fileUpload: 'mdi-tray-arrow-up',
        documentInstanceIdentifier: ' ',
        user: 'mdi-account-circle-outline',
        number: 'mdi-numeric',
        textInput: 'mdi-alphabetical',
        label: 'mdi-alpha-a-circle-outline',
        combobox: 'mdi-list-status',
        location: 'mdi-map-marker-outline',
        checkbox: 'mdi-checkbox-blank-outline'
    },
};
